name: ${PROJECT_NAME:-fastapi-mcp-template}
services:
  fastapi-mcp-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ../app:/app/app
    environment:
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
      - READ_ONLY_MODE=${READ_ONLY_MODE:-false}
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
